### ISSUE TITLE
Broken links from 9/7 SiteImprove report

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1631]
The following links are confirmed to be broken. Please fix the ones you're assigned to, then check them off.

- [x] **[Great Plates](https://covid19.ca.gov/restaurants-deliver-home-meals-for-seniors/)**: In accordion under San Diego County,  "apply for meals online" is broken. Remove or replace. @ashleydraper 

- [x] **[Homepage](https://covid19.ca.gov/) and all translated versions of it**: Missing image file https://covid19.ca.gov/i/img/hero.jpg @aaronhans @carterm 

- [x] **[Housing and homelessness](https://covid19.ca.gov/housing-and-homelessness/)**:  Link to housingiskey.com times out.  They probably don't have their redirects set up correctly. Make sure the link is exactly this: **http://housingiskey.com** (no **https**, no **www**). @ashleydraper

**Comment by ashleydraper** [comment]
@thepegisin What does it mean that "housingiskey.com times out." Does the site eventually show a 404 error?

**Comment by ashleydraper** [comment]
@thepegisin 
Housing and Great Plates links are fixed

**Comment by thepegisin** [comment]
9/14 report: Two of the broken links above are still there.

- [ ] @ashleydraper: This link at the bottom of **Housing and homelessness** still times out. Remove the "s" from https and the "www" and that should fix it. 
<img width="522" alt="2020-09-15_10-49-07" src="https://user-images.githubusercontent.com/63249920/93246289-6f45c600-f741-11ea-8232-fe3ed97feaf0.png">

- [ ] @carterm @aaronhans The following instances of hero.jpg are still missing:
<img width="393" alt="2020-09-15_10-48-04" src="https://user-images.githubusercontent.com/63249920/93246378-88e70d80-f741-11ea-8ccf-50c89130208b.png">

**Comment by ashleydraper** [comment]
Sorry, sorry, sorry! Thanks for the screenshot. That link should be the same as the first HousingIsKey link toward the top. I've updated it and the change should be live momentarily :).

**Comment by thepegisin** [comment]
Awesome! Thank you.

**Comment by thepegisin** [comment]
**hero.jpg** image above still showing as a broken link as of 9/22. @aaronhans @carterm

**Comment by aaronhans** [comment]
I think we have sorted this out now and it should stop getting reported
